### PR TITLE
Add the checkout location to the nginx extra config.

### PR DESCRIPTION
**Pull request by coderbyheart**
We need the location of the current checkout to configure static routes.

Example:

```
nginx_https_extra_config: |
  location /dashboard/ {
    alias {checkout_location}/build/dashboard/;
    index index.html;
  }
```

`{checkout_location}` needs to be replaced with the actual location of the checkout.

NOTE: this breaks the `restart` command as it doesn't know about the check out at all.

### CODE REVIEW

**Comment by coderbyheart** [comment]
@Delphinator Can you have a look at this if the change is understandable? How do we achieve this for the `restart` command?

**Comment by JensGutermuth** [comment]
Serving static files from a checkout is already possible using a `StaticRunner`. The name isn't perfect as it doesn't run anything and just configures nginx. Naturally this also works with the `restart` command.

This use case is covered in the example configuration of a [repo](https://github.com/fintura/pyPaaS/blob/master/example-configuration/repos/node-js-sample.yml#L33) and a [domain](https://github.com/fintura/pyPaaS/blob/master/example-configuration/domains/node-js-sample.example.com.yml#L12).

**Comment by coderbyheart** [comment]
Well, we use the `NginxBackend` runner for this host and need to serve static files, too.

**Comment by JensGutermuth** [comment]
You can have as many runners per repo and domain as you like. In a repo they each have a unique name (the key in the mapping) and in a domain they have a unqiue path (say `/dashboard/`). The example configuration results in something like

```
upstream backend_node-js-sample {
    server 127.0.0.1:60001;
    server 127.0.0.1:60002;
}

server {
    listen 80;
    server_name node-js-sample.example.com;
    location / {
        proxy_pass http://backend_node-js-sample;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    }
    location /public {
        alias /home/deploy/checkouts/node-js-sample/24sesd-20151101_1212/public;
    }
    gzip on; # there is a nginx_extra_config key in the domain config, this is not here by default
}
```

**Pull request closed without merging**
